### ISSUE TITLE
[1.3] using keyboard hotkeys to adjust gamespeed doesn't affect the slider

### ISSUE THREAD

**Issue by Washeh** [FA-mods/SupremeScoreBoard#1]
using the + or - hotkeys to change gamespeed (tested only in replays) does not affect the game speed slider of the scoreboard (version 1.3)

**Comment by speed2CZ** [comment]
Also game speed indicator (speed set by an observer vs actual game speed) is not properly updating. First number is always 0

**Comment by HUSSAR-mtrela** [comment]
thanks guys for reporting it and I will fix it soon

**Comment by HUSSAR-mtrela** [comment]
@Washeh and @speed2CZ  it's late fix but I finally go to it :D
