### ISSUE TITLE
[1.3] latest version of mod is not showing up in mod vault

### ISSUE THREAD

**Issue by heelix** [FA-mods/SupremeScoreBoard#11]
I see others playing with 1.3, but the latest vault version looks like it is v1.2 V1.  That intended?

**Comment by HUSSAR-mtrela** [comment]
@heelix last time I checked the mod vault was broken and I could not upload new version of my mod so I posted instructions how to download v1.3 from this website:
https://github.com/FA-mods/SupremeScoreBoard#installation

**Comment by HUSSAR-mtrela** [comment]
version 2.0 is in the mod vault
