### ISSUE TITLE
Player icons/names do not flash when someone pings

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [FA-mods/SupremeScoreBoard#12]
In org. score board, icons/names flash when someone pings but that does not happen anymore in SSB

**Comment by Justify87** [comment]
Thx for all your work. But this is by far the most annoying thing. If by any chance u r in a super mood to prioritize this I'd buy u some pizza and hooker

**Comment by HUSSAR-mtrela** [comment]
@Justify87 it's late fix but I finally go to it :D
