### ISSUE TITLE
Hide the score screen with default key to hide all UI elements

### ISSUE THREAD

**Issue by speed2CZ** [FA-mods/SupremeScoreBoard#14]
There is a hotkey to hide all UI elements, by default Ctrl-Shift-F1 which hides all the UI stuff (including the arrows to show them again). It's used mainly for taking screenshots and stuff and it would be nice if it hid your score screen as well.

**Comment by HUSSAR-mtrela** [comment]
@speed2CZ this should be fixed in the v4 of SSB

**Comment by speed2CZ** [comment]
Nice!
