### ISSUE TITLE
SBB crashes when using custom army colors

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [FA-mods/SupremeScoreBoard#15]
Root causes
- adding new army colors
- changing army colors

Fix:
Replace hardcoded army colors by colors loaded from gamecolors.lua

Reported by:
BlackYps, Philip Fry

**Comment by BlackYps** [comment]
I created a pull request that should fix the crashing. Removing the hardcoded colors to improve the functionality is still a good idea. At the moment the new colors would default to white in the scoreboard.

**Comment by HUSSAR-mtrela** [comment]
closing due to a fix in PR #16
