### ISSUE TITLE
Does not display properly with UI scale

### ISSUE THREAD

**Issue by Talia-12** [FA-mods/SupremeScoreBoard#17]
Due to the high resolution of my monitor, I play with the UI Scale setting set to 200%. However, this does not work well with the SupremeScoreBoard mod, which does not update its UI elements properly to deal with the scaling. This results in the UI looking as below.

![broken](https://user-images.githubusercontent.com/17948170/86438389-cabf0500-bd49-11ea-813c-9cd87642cf3b.png)

In contrast, when the UI scale is set back to 100% with all other settings left as before, the scoreboard displays as expected as can be seen below.

![working](https://user-images.githubusercontent.com/17948170/86438394-cc88c880-bd49-11ea-8916-949f0dc6ae76.png)

**Comment by HUSSAR-mtrela** [comment]
@Talistan12 I fixed this issue in version 6 (see mod vault)
